language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
env:
  - TEST_HIREDIS=0
  - TEST_HIREDIS=1
install:
  - pip install -e . --use-mirrors
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8 --use-mirrors; fi"
  - "if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis --use-mirrors; fi"
script: "if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,doc,build,*.egg .; else python setup.py test; fi"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1
    - python: "3.3"
      env: TEST_PEP8=1
  exclude:
    - python: "2.5"
      env: TEST_HIREDIS=1
